services:
  - type: web
    name: kemet-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/AhmedmMhmoud2001/kemet-backend
    branch: main
    rootDir: .
